feat: add endpoint to get all products
ArianeBeltrao/product-service pull request #7
Opened 2024-12-23 21:49 UTC by ArianeBeltrao

feat: endpoint to get all existing products

2024-12-24 02:05 UTC, Arthuralentejo requested changes

2024-12-24 02:05 UTC, Arthuralentejo commented on route/product_router.py
> +async def get_all_products():
Adicione um response model indicando qual é o tipo do dado que será retornado por esse endpoint

2024-12-24 02:05 UTC, Arthuralentejo commented on route/product_router.py
> +async def get_all_products():
Remover async

2024-12-24 02:05 UTC, Arthuralentejo commented on storage/product_storage.py
> +        except Exception as ex:
Capturar apenas DatabaseError

2024-12-26 20:22 UTC, AurelioNM approved these changes

2024-12-27 22:35 UTC, Arthuralentejo requested changes
Uma duvida geral que tive é: 

Vcs não estão usando soft delete nessa tabela? Isso afeta a forma como o get é feito.

2024-12-27 22:35 UTC, Arthuralentejo commented on storage/product_storage.py
> +        except Exception as ex:
Evitar capturar exception generica, o except anterior ja basta.

2024-12-27 22:35 UTC, Arthuralentejo commented on storage/product_storage.py
> +                        '{product.id}',
Eu errei ao dizer no dia da call que a biblioteca resolveria sozinho essa injeção de parametros aqui, o mais seguro é passar como parametros separados igual ao que esta sendo feito aqui 
https://github.com/ArianeBeltrao/product-service/blob/4872fbad3a3ee96d8e82300545b1ef0f88f47d54/storage/product_storage.py#L79

2024-12-27 22:35 UTC, Arthuralentejo commented on storage/product_storage.py
> +        except Exception as ex:
Mesma coisa sobre exception generica

2024-12-27 22:39 UTC, Evandro-Ladislau approved these changes

2024-12-27 23:16 UTC, Arthuralentejo approved these changes

2024-12-27 23:20 UTC, merged