Feat/create update endpoint
ArianeBeltrao/product-service pull request #8
Opened 2024-12-24 16:28 UTC by Evandro-Ladislau

feat: create update endpoint.

2024-12-24 16:33 UTC, didibrabosa reviewed
ficou mídia!

2024-12-24 16:34 UTC, didibrabosa commented on route/product_router.py
> +async def update_product(product_id: str, product: Product):
async?? pq?

2024-12-24 16:49 UTC, Evandro-Ladislau commented on route/product_router.py
> +async def update_product(product_id: str, product: Product):
Muito basicamente, o async é usado para criar funções que esperam por algo que demora, sem bloquear outros processamentos do sistema.
Porém, como o Arthur mencionou na review, tem coisas mais complexas por trás disso. Como ainda não tenho esse conhecimento mais aprofundado sobre o async, segui a instrução dele e fiz a remoção.

Bem observado Diego, obrigado!

2024-12-24 17:40 UTC, michaelrodriguess commented on storage/product_storage.py
> +                    WHERE id = '{id}';
aqui temos uma possivel falha de SQL injection, por conta da interpolação para os campos do banco de dados. se eu passar um id -> id = '1'; DROP TABLE products; --'
a Query resultante vai ser: 
 'UPDATE products 
 SET 
    name = 'value',
    description = 'value',
    price = 100,
    quantity = 10,
    active = true,
    created_at = '2024-01-01',
    updated_at = NOW()
WHERE id = '1'; DROP TABLE products; --';

E Isso poderia apagar toda tabela products. O ideal é usar a **parametrização** que é  o operador **%s** para evitar o SQL Injection.   Ficaria algo como:
"""UPDATE products SET name = %s WHERE id = %s;""",(product.name, id). Fazendo assim os valores são passados como parâmetros. O cursor.execute com parâmetros usa queries preparadas, e o banco de dados sanitiza automaticamente os valores antes de inseri-los na query.

2024-12-24 17:42 UTC, michaelrodriguess commented on storage/product_storage.py
> +            cursor.close()
creio que não é preciso usar o cursor.close() aqui por conta que o with self.db.cursor fecha automaticamente

2024-12-26 21:31 UTC, Evandro-Ladislau commented on storage/product_storage.py
> +                    WHERE id = '{id}';
Você tem razão, eu sei disso. Inclusive, comentamos sobre isso no code review. Faltou um pouco de atenção da minha parte mesmo. Obrigado por pontuar!

2024-12-27 22:32 UTC, Arthuralentejo requested changes

2024-12-27 22:32 UTC, Arthuralentejo commented on service/product_service.py
> +        product.updated_at = datetime.now()
Será que é aqui que deveria fazer isso?

2024-12-28 01:15 UTC, Arthuralentejo requested changes, later dismissed

2024-12-28 01:15 UTC, Arthuralentejo commented on storage/product_storage.py
> +            return self.get_product_by_id(product.id)
Mano aqui vc ta fazendo sua aplicação fazer uma nova query pra buscar o produto que vc atualizou, então toda requisição de update na real acabaria fazendo duas queries,. Agora pensa q seu sistema recebe 10k requests por minuto, isso não parece ser escalável né? 

Acho que vc pode retornar a model que vc ta usando pra salvar, ja que vc ta atualizando a data do updated at dela na service

2024-12-30 17:37 UTC, Raph2ll commented on route/product_router.py
> +async def update_product(product: Product):
Esse async é necessário aq ?

2024-12-30 17:38 UTC, Raph2ll commented on storage/product_storage.py
> +                    WHERE id = %s;
Falta o and active = true

2024-12-30 18:05 UTC, GS0606 commented on route/product_router.py
sua router tá criando a função com async !

2024-12-31 13:54 UTC, AurelioNM approved these changes

2024-12-31 13:54 UTC, AurelioNM commented on storage/product_storage.py
> +            cursor.close()
como vc já esta usando o `with self.db.cursor()`, não precisa colocar o `cursor.close()` aqui. Pq o with já é responsável por fechar o recurso, após o uso
So precisa do `self.db.commit()`

2024-12-31 13:54 UTC, AurelioNM commented on .env.example
Pq deletou o env.example? É importante que ele esteja ai pra que quem for executar o projeto saiba quais variaveis precisam ser preenchidas

2024-12-31 13:54 UTC, AurelioNM commented on route/product_router.py
> +    product_updated = service.update_product(product)
Importante logar quando a requisição termina, e o retorno dela. Assim como as outras rotas

2024-12-31 13:54 UTC, AurelioNM commented on storage/product_storage.py
> +            self.db.commit()
O `self.db.commit()` pode ficar dentro do try, e esse finally pode ser removido.
So adicionar um `self.db.rollback()` no except, pra fechar a transação no DB em caso de erro

2024-12-31 13:54 UTC, AurelioNM commented on service/product_service.py
> +        product.updated_at = datetime.now()
Fui eu que sugeri :)

Pra manter a consistencia do que vai ser setado na coluna de updated_at
E a response da API

2024-12-31 13:54 UTC, AurelioNM commented on storage/product_storage.py
> +            return self.get_product_by_id(product.id)
Tem um comando SQL que da pra colocar no Update, q é o RETURNING
Ele retorna os valores atualizados das colunas

2024-12-31 13:54 UTC, AurelioNM commented on storage/product_storage.py
> +                    WHERE id = %s;
Nao acho q seja obrigatório. O put tem q ser capaz de atualizar qualquer produto, independente se ta ativo ou nao

2024-12-31 15:58 UTC, ArianeBeltrao approved these changes

2024-12-31 15:58 UTC, merged